# Algorithm for Finding the Shortest Path in a Grid
## Description of the Problem
Having a rectangular grid (of size height $\times$ width) where each cell has a random integer between 0 and 9. An agent starts at the upper-left corner of the grid and must reach the bottom-right corner of the grid as fast as possible. The time spent on a cell is the number on this cell.
<br>
<br>
We can model this problem with a graph where each cell is a vertex and the number on a cell is the edge of this vertex from a neighbour vertex in the graph. Each vertex (cell) can have at most 4 neighbours (left-up-right-bottom)



In [7]:
import numpy as np 
from copy import deepcopy

In [8]:
# BUILD THE GRID
from gridMaker import Grid

grid = Grid(10,12)  # AN INSTANCE OF THE GRID CLASS
sample_grid = grid.make_grid()  # MAKE THE GRID

print(sample_grid)



[[3 0 9 6 1 2 3 2 1 4 5 3]
 [8 1 2 2 4 6 6 5 0 7 2 3]
 [6 1 9 2 8 4 8 1 2 5 2 4]
 [3 8 1 9 7 9 5 2 6 4 7 5]
 [4 0 7 9 7 4 4 0 0 4 9 7]
 [1 0 4 1 3 3 5 7 7 2 3 9]
 [2 6 2 8 8 3 2 6 5 2 6 5]
 [5 2 6 6 2 1 5 1 7 2 1 5]
 [3 9 7 2 6 8 5 9 1 2 3 2]
 [1 7 5 1 1 1 5 4 3 2 5 9]]


## Random Search

An agent can decide to go to a neighbour cell based on a random choice generated from a uniform distribution. To model this method we generate a class and find the time it takes to move from the source to a target destination and compute the average time for 1000 trials of this kind. 

In [9]:
from RandomSearch import RandomSearch

# MAKE AN OBJECT OT THE RANDOMSEARCH CLASS 
algorithm = RandomSearch(sample_grid, target=(10,12))

# DICTIONARY TO ADD TRIALS' PATHS AND DISTANCES (TIMES)
paths = {'path':[], 'dist':[]}
for i in range(1000):
    dist, path = algorithm.find_the_path()
    paths['path'].append(path)
    paths['dist'].append(dist)

# THE AVERAGE TIME OF ALL TRIALS AND SMAPLE PATH FOR ONE OF THEM 
average_distance = np.mean(paths['dist'])
print('average time \n')
print(average_distance, '\n')
print('one sample path \n')
print(paths['path'][0], '\n')
print('and its time \n')
print(paths['dist'][0])

average time 

2936.562 

one sample path 

[(0, 0), (0, 1), (0, 0), (0, 1), (0, 2), (1, 2), (2, 2), (1, 2), (0, 2), (0, 1), (0, 2), (0, 1), (0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5, 2), (4, 2), (4, 3), (5, 3), (6, 3), (7, 3), (7, 2), (7, 1), (7, 0), (7, 1), (6, 1), (7, 1), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 6), (9, 6), (9, 7), (9, 8), (9, 9), (9, 8), (9, 9), (9, 10), (8, 10), (9, 10), (8, 10), (9, 10), (9, 9), (9, 10), (8, 10), (8, 11), (8, 10), (9, 10), (9, 11)] 

and its time 

[240.]


## Suboptimal Heuristic Solution
A heuristic method to find the shortest path between the source (upper-left corner) and a target vertex in a random size graph can be a sequence of best moves on each steps to find the suboptimal solution to the problem. The agent starts at the source and finds the best action (move) among the feasible solutions (its neighbours). Because all the possible targets in the grid are on the bottom-right side of the agent, we assume that each cell has just two feasible neighbours which are the right and the bottom cells of the current cell. The agent walks through the grid and in each step it chooses to go to the right or to the bottom, however, it cannot move to a cell where has a location number on the grid greater than the number of the target location based on the grid coordinates (upper-left corner).

In [10]:
from BaselineAlgorithm import BASP

# MAKE AN INSTANCE OF BASP
algorithm = BASP(sample_grid, target=(10,12))
path, dist = algorithm.find_the_path()

# RESULTS
print('sample grid \n')
print(sample_grid,'\n')
print('path \n')
print(path,'\n')
print('time \n')
print(dist,'\n')

sample grid 

[[3 0 9 6 1 2 3 2 1 4 5 3]
 [8 1 2 2 4 6 6 5 0 7 2 3]
 [6 1 9 2 8 4 8 1 2 5 2 4]
 [3 8 1 9 7 9 5 2 6 4 7 5]
 [4 0 7 9 7 4 4 0 0 4 9 7]
 [1 0 4 1 3 3 5 7 7 2 3 9]
 [2 6 2 8 8 3 2 6 5 2 6 5]
 [5 2 6 6 2 1 5 1 7 2 1 5]
 [3 9 7 2 6 8 5 9 1 2 3 2]
 [1 7 5 1 1 1 5 4 3 2 5 9]] 

path 

[(0, 0), (0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (6, 5), (7, 5), (7, 6), (7, 7), (7, 8), (8, 8), (8, 9), (9, 9), (9, 10), (9, 11)] 

time 

[48.] 



## Conclusion on Baseline
We can see that the baseline algorithm is far better than a random based decision and it is also faster in terms of computation. If the grid is big then the computation might be exhaustive for the random search algorithm.  

## Dijkstra's Algorithm
One of the well-known and efficient algorithms to find the shortest path in a graph is [Dijkstra's algorithm] (https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm). For a given source vertex in the graph, this algorithm finds the shortest path from the source to any vertices in the graph. This algorithm uses positive intigers or real numbers labels which are totally ordered.
<br>
<br>
In the environment of the problem stated above, the starting vertex (source) is the upper-left corner and the target is the bottom-right corner of the grid. Dijkstra's algorithm assumes each vertex distance is the distance between source and that vertex. The steps for finding the shortest path in this algorithm is as follows:

> 1. Create a set of unvisited cells containing all the cells.
2. Set the initial distance of all cells to infinity and assign zero to the source.
3. Set the source as the current cell.
4. Calculate the distance of all unvisited neighbours to the current cell. Add the value of current distance to the calculated distances for each feasible neighbour. If the distance for a neighbour is less than the current value of it then modify this value with the new calculated distance. This is the distance from source to the neighbour through the current cell.
5. After considering all the feasible neighbours of the current cell, mark the current cell as visited and remove it from the unvisited cells.
6. If the target cell marked as visited then terminate the process.
7. Otherwise, set the unvisited cell with the smallest tentative distance as the new current cell, and go back to step 4.

We can also stop the process when the target has the smallest tentative distance among all unvisited cells. 

In [11]:
from DijkstraAlgorithm import Dijkstra

# MAKE AN INSTANCE OF DIJKSTRA
algorithm = Dijkstra(grid=sample_grid, target=(10,12))
minimum_distances, target_distance, target_path = algorithm.find_the_shortest_path()

# RESULTS
print('Sample grid:\n')
print(sample_grid,'\n')
print('Minimum Distances Matrix from the Source:\n')
print(minimum_distances,'\n')
print('min time from the target:\n')
print(target_distance,'\n')
print("Dijkstra's Shortest Path from Source to Target:\n")
print(target_path)

Sample grid:

[[3 0 9 6 1 2 3 2 1 4 5 3]
 [8 1 2 2 4 6 6 5 0 7 2 3]
 [6 1 9 2 8 4 8 1 2 5 2 4]
 [3 8 1 9 7 9 5 2 6 4 7 5]
 [4 0 7 9 7 4 4 0 0 4 9 7]
 [1 0 4 1 3 3 5 7 7 2 3 9]
 [2 6 2 8 8 3 2 6 5 2 6 5]
 [5 2 6 6 2 1 5 1 7 2 1 5]
 [3 9 7 2 6 8 5 9 1 2 3 2]
 [1 7 5 1 1 1 5 4 3 2 5 9]] 

Minimum Distances Matrix from the Source:

[[ 0.  0.  9. 11. 10. 12. 15. 17. 18. 22. 27. 30.]
 [ 8.  1.  3.  5.  9. 15. 21. 22. 18. 25. 27. 30.]
 [ 8.  2. 11.  7. 15. 19. 27. 21. 20. 25. 27. 31.]
 [11. 10. 11. 16. 22. 28. 28. 23. 26. 29. 34. 36.]
 [14. 10. 17. 24. 25. 25. 27. 23. 23. 27. 36. 43.]
 [11. 10. 14. 15. 18. 21. 26. 30. 30. 29. 32. 41.]
 [13. 16. 16. 23. 26. 24. 26. 32. 35. 31. 37. 42.]
 [18. 18. 22. 28. 27. 25. 30. 31. 38. 33. 34. 39.]
 [21. 27. 29. 30. 33. 33. 35. 40. 36. 35. 37. 39.]
 [22. 29. 34. 31. 32. 33. 38. 42. 39. 37. 42. 48.]] 

min time from the target:

39.0 

Dijkstra's Shortest Path from Source to Target:

[(0, 0), (0, 1), (1, 1), (1, 2), (1, 3), (1, 4), (0, 4), (0, 5), (0, 6), (

## Conclusion on Dijkstra's Algorithm
Dijkstra's algorithm converges to the global minimum for non-negative edges. As we stated our before the problem environment satisfies this condition. Therefore, we always have a solution for this problem that we defined. An induction proof for Dijkstra's algorithm can be as follows:
> 1. If there is only one visited cell say that the source the hypothesis is trivial.
2. Let assume for each visited cell (v), $dist[v]$ is the shortest path from the source to (v) just using the visited cells.  
3. Let assume we have n-1 visited nodes. We choose an edge (vu) such that (u) is an unvisited cell which has the smallest tentative distance $dist[u]$ among the unvisited cells, and $dist[u] = dist[v] + length[v,u]$.
4. If there is another unvisited cell (w) which the shortest path from source to (u) passes through (w) then it contradicts the fact that (u) has the smallest $dist[u]$ among unvisited cells say that $dist[w] < dist[u]$, which creates a contradiction.
5. If there is another visited cell that has the shortest path to u then $dist[u] = dist[w] + length[w,u]$ which creates a contradiction again to the fact that $dist[u] = dist[v] + length[v,u]$.
6. This is true for all other unvisited cells (w). Because, if there were another way which goes through unvisited cell (u) then we would have updated it previously.
7. The shortest pass for all cells can be find using just visited cells.
8. Therefore, $dist[v]$ is the shortest distance.

## Ant Colony Optimization
One of the well-known algorithms to find the shortest path in a graph is [Ant Colony System (ACS-paper)] (http://www.idsia.ch/~luca/acs-ec97.pdf). For a given source vertex in the graph, this algorithm finds the shortest path from the source to a specified target. These sort of algorithms diversified to solve a wide range of problems such as Routing Vehicles, RFID-Tags, Image Processing, Device Sizing Problem, and etc.
<br>
<br>
In the environment of the problem stated above, the starting vertex (source) is the upper-left corner and the target is the bottom-right corner of the grid. In Ant Colony Optimization (ACO) algorithm, a set of artificial ants (agents-ants) search for approximate solution to a given optimization problem. These ants gradually build solutions by moving on the grid. The solution construction process is stochastic and biased by a $pheromone~model$. The parameters of $phromone~model$ are modified at runtime by the ants. These parameters are associated with graph components (edges or vertices). ACS construction steps can be as follows:
> 1. A set of m artificial ants construct solutions from a finite set of avaible solution components $C = \{v_{i,j} \mid 1 \leq i,j \leq n \}$. A solution construction starts with a set of empty partial solutions $s^p$. At each construction step, the current partial solution is extended by adding a feasible solution component from the set of feasible neighbours $N(s^p)$. This process can be regarded as the path.
2. The process of selecting a solution component among the feasible neighbours is done probabilistically at each construction step. The transition probability $p(v_{i,j} \mid s_k^p)$ of the k-th ant moving from vertex i to j is given by:
<br>
<br>
A random variable q uniformly distributed over $[0,1]$ and an initial probability $q_0$. If $q \leq q_0$, then among the feasible components on this step, the component which maximizes the product $\tau_{i,j}^\alpha \cdot \eta_{i,j}^\beta$ is chosen. Otherwise as follows:

\begin{equation}
    p(v_{i,j} \mid s_k^p) =
        \begin{cases}
            \frac{\tau_{i,j}^\alpha \cdot \eta_{i,j}^\beta}{\sum\limits_{v_{i,l} \in N(s_k^p)}\tau_{i,l}^\alpha \cdot \eta_{i,l}^\beta}  & \text{if } j \in N(s_k^p) \\
            0 & \text{Otherwise}
        \end{cases}
            
\end{equation}
 
> where $\tau_{i,j}$ and $\eta_{i,j}$ are repectively the pheromone value and the heuristic value associated with component $v_{i,j}$. Furthermore, $\alpha$ and $\beta$ are positive real parameters whose values control the relative importance of pheromone value versus the heuristic information $\eta_{i,j} = \frac{1}{d_{i,j}}$, where $d_{i,j}$ is the length of component $v_{i,j}$.
<br>

> 3. A local pheromone update is performed by all ants after each construction step. Each ant only applies it to the last edge traversed:

\begin{equation}
    \tau_{i,j} = (1 - \phi) \tau_{i,j} + \phi \tau_0 
\end{equation}

> where $\phi \in (0,1]$ is the pheromone decay coefficient, and $\tau_0$ is the initial value of the pheromone. The goal of local update is to diversify the search of subsequent ants during one iteration.
<br>

> 4. At the end of the construction process, an offline pheromone update is performed. This update is done by the best ant only on visited edges by this ant as the equation given by:
\begin{equation}
    \tau_{i,j} = (1 - \rho) \tau_{i,j} + \Delta \tau_{i,j}^{best}
\end{equation}

> where $\Delta \tau_{i,j}^{best} = \frac{1}{L_{best}}$ for the visited edges by the best ant and zero Otherwise. $L_{best}$ can be either the length of the best tour found in the current iteration or the best solution up to the current iteration of trial (We implement the latter one).
<br>

> 5. The stopping criterion can be a certain number of iteration or after that there is no improvment in the pheromone values or the best solution found after a patience number (We implement the first one).

In [12]:
from ACO import ACS

# MAKE AN INSTANCE OF ACS 
algorithm = ACS(sample_grid, target=(10,12))
path, time = algorithm.find_the_shortest_path(n_ants=10,
                                              n_iterations=200,
                                              beta=1.3,
                                              callbacks=['absolute_difference',
                                                        4,
                                                        4])
# RESULTS
print('sample grid\n')
print(sample_grid,'\n')
print('the path\n')
print(path,'\n')
print('time to reach the target\n')
print(time)

sample grid

[[3 0 9 6 1 2 3 2 1 4 5 3]
 [8 1 2 2 4 6 6 5 0 7 2 3]
 [6 1 9 2 8 4 8 1 2 5 2 4]
 [3 8 1 9 7 9 5 2 6 4 7 5]
 [4 0 7 9 7 4 4 0 0 4 9 7]
 [1 0 4 1 3 3 5 7 7 2 3 9]
 [2 6 2 8 8 3 2 6 5 2 6 5]
 [5 2 6 6 2 1 5 1 7 2 1 5]
 [3 9 7 2 6 8 5 9 1 2 3 2]
 [1 7 5 1 1 1 5 4 3 2 5 9]] 

the path

[(0, 0), (0, 1), (1, 1), (2, 1), (2, 0), (3, 0), (4, 0), (4, 1), (5, 1), (5, 0), (6, 0), (7, 0), (8, 0), (9, 0), (9, 1), (9, 2), (9, 3), (9, 4), (9, 5), (9, 6), (9, 7), (9, 8), (9, 9), (9, 10), (9, 11)] 

time to reach the target

[70.]
